# Generated by Django 5.0.6 on 2024-06-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_payment_link_payment_stripe_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('completed', 'Завершен'), ('failed', 'Неудача')], default='pending', max_length=20, verbose_name='статус оплаты'),
        ),
    ]
