# Generated by Django 5.0.6 on 2024-06-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, verbose_name='цена'),
            preserve_default=False,
        ),
    ]
